### ISSUE TITLE
Migrations are broken in Django 1.7.4

### ISSUE THREAD

**Issue by outime** [gregmuellegger/django-sortedm2m#44]
I've just upgraded from Django 1.7.1 to Django 1.7.4 straight. There was one issue in the Django project (check https://code.djangoproject.com/ticket/24104) which was making some other app to break when running migrations with SQLite at least (typically used in tests).

I tried to run the tests in Django 1.7.3 and django-sortedm2m fields were fine, so it can very well be related with that issue. Hopefully this is enough to address the problem quickly.

Here is the traceback:

```
Running migrations:

  Applying a.0001_initial... OK

  Applying b.0001_initial... OK

  (...)

  Applying c.0001_initial... OK

  Applying c.0002_auto_20141110_1027...Traceback (most recent call last):

  File "manage.py", line 9, in <module>

    execute_from_command_line(sys.argv)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line

    utility.execute()

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 50, in run_from_argv

    super(Command, self).run_from_argv(argv)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv

    self.execute(*args, **options.__dict__)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 71, in execute

    super(Command, self).execute(*args, **options)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute

    output = self.handle(*args, **options)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 88, in handle

    failures = test_runner.run_tests(test_labels)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/test/runner.py", line 147, in run_tests

    old_config = self.setup_databases()

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/test/runner.py", line 109, in setup_databases

    return setup_databases(self.verbosity, self.interactive, **kwargs)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/test/runner.py", line 299, in setup_databases

    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/db/backends/creation.py", line 377, in create_test_db

    test_flush=True,

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command

    return klass.execute(*args, **defaults)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute

    output = self.handle(*args, **options)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle

    executor.migrate(targets, plan, fake=options.get("fake", False))

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate

    self.apply_migration(migration, fake=fake)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration

    migration.apply(project_state, schema_editor)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply

    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 37, in database_forwards

    field,

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 176, in add_field

    self._remake_table(model, create_fields=[field])

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 144, in _remake_table

    self.quote_name(model._meta.db_table),

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 102, in execute

    cursor.execute(sql, params)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute

    return self.cursor.execute(sql, params)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute

    return self.cursor.execute(sql, params)

  File "/home/user/virtualenv/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute

    return Database.Cursor.execute(self, query, params)

django.db.utils.OperationalError: table shop_shop__new has no column named shop_actions
```

`shop_actions` is a sortedm2m field and is the only type of field breaking.

**Comment by gregmuellegger** [comment]
This was fixed as with #43 
The fix is not yet part of a PyPI release. I hope to get this out ASAP.
